- ckanext/versioned_datastore/logic/action.py
- ckanext/versioned_datastore/logic/auth.py
- ckanext/versioned_datastore/logic/schema.py
- ckanext/versioned_datastore/plugin.py
This allows full access to all of the power of the backend through the API even though there's no frontend for it all yet.
> Allow raw elasticsearch queries into the backend

- ckanext/versioned_datastore/plugin.py
Say bye bye to IResourceUrlChange, it just confuses things. The notify function is pretty dodgy but this cleans up the usage of it a little bit to make it easier to understand. This commit also just tidies up a couple of `inherit=True`s that didn't need to be in use.
Partial closure of https://github.com/NaturalHistoryMuseum/ckanext-versioned-datastore/issues/4.
> Refactor the notify usage to be a bit more predictable

- ckanext/versioned_datastore/lib/details.py
- ckanext/versioned_datastore/lib/utils.py
- ckanext/versioned_datastore/model/details.py
We should know the order of the columns as we store it during ingestion, so we should use it! This was implemented in a previous commit but it was done badly and needed reverting. This PR implements the work correctly.
> Present the correct column order

- ckanext/versioned_datastore/lib/importing.py
- ckanext/versioned_datastore/lib/indexing/indexing.py
- ckanext/versioned_datastore/lib/ingestion/ingesting.py
- ckanext/versioned_datastore/lib/ingestion/readers.py
- ckanext/versioned_datastore/lib/ingestion/utils.py
- ckanext/versioned_datastore/lib/queuing.py
- ckanext/versioned_datastore/lib/utils.py
- add titles to import/index jobs
- split ingestion specific utils into their own utils module
> Few small tidy ups

- ckanext/versioned_datastore/lib/stats.py
- requirements.txt
This has already been done on the `upgrade/main` branch but is needed on this branch too for the 18.04 upgrade.
> Update to eevee v1.1.1

- ckanext/versioned_datastore/lib/query/query_log.py
- ckanext/versioned_datastore/logic/actions/multisearch.py
This will be useful to get an idea of the types of queries users are doing through the new integrated search page.
> Log queries so that we can see what's happening!

- ckanext/versioned_datastore/lib/downloads/utils.py
This fixes a bug where nested fields weren't being included in the final filtered dict for a couple of reasons:
- the base field was checked when it won't exist in the field counts (e.g. `associatedMedia`)
- lists of dicts weren't handled correctly
Reported by the bug specialist @bwprice
> Correctly handle lists of nested dicts

- ckanext/versioned_datastore/interfaces.py
- ckanext/versioned_datastore/lib/downloads/download.py
- ckanext/versioned_datastore/lib/downloads/dwc/archive.py
- ckanext/versioned_datastore/lib/downloads/dwc/writer.py
- ckanext/versioned_datastore/lib/downloads/transform.py
- ckanext/versioned_datastore/logic/actions/downloads.py
- ckanext/versioned_datastore/logic/schema.py
Basic system for transforming data before writing to download files, configured by request args. So far just one transformation: turning an ID into a URL.
> Data transformations

- ckanext/versioned_datastore/lib/downloads/download.py
- ckanext/versioned_datastore/lib/downloads/xlsx.py
- ckanext/versioned_datastore/logic/actions/downloads.py
- ckanext/versioned_datastore/logic/actions/multisearch.py
- ckanext/versioned_datastore/logic/schema.py
- ckanext/versioned_datastore/routes/search.py
- docker-compose.yml
- setup.cfg
- tests/test_xlsx_downloader.py
- Download with slug or DOI (#58)
- Add an XLSX file download option (#59)
> Release 2022-04-25

- ckanext/versioned_datastore/logic/actions/help.py
- ckanext/versioned_datastore/logic/actions/multisearch.py
- ckanext/versioned_datastore/logic/auth.py
- ckanext/versioned_datastore/logic/schema.py
- ckanext/versioned_datastore/plugin.py
- New action and UI to edit slugs (https://github.com/NaturalHistoryMuseum/ckanext-versioned-datastore/pull/61)
> Release 2022-05-03

- ckanext/versioned_datastore/logic/actions/help.py
- ckanext/versioned_datastore/logic/actions/multisearch.py
- ckanext/versioned_datastore/logic/auth.py
- ckanext/versioned_datastore/logic/schema.py
- ckanext/versioned_datastore/plugin.py
We'll need this for new search UI and I need it sooner for some small modifications v-factor beetles page.
> Add integrated value autocomplete action

- ckanext/versioned_datastore/logic/actions/basic_search.py
Fixes https://github.com/NaturalHistoryMuseum/ckanext-versioned-datastore/issues/68
> Add default version to datastore_query_extent action

- ckanext/versioned_datastore/logic/actions/basic_search.py
- setup.cfg
- https://github.com/NaturalHistoryMuseum/ckanext-versioned-datastore/pull/69
> Release 22/08/22

- README.md
- setup.cfg
> Weekly release 2022-10-03

- docker-compose.yml
- docker/Dockerfile
- test.ini
Contains a few small modifications:
- https://github.com/NaturalHistoryMuseum/ckanext-versioned-datastore/pull/78
- https://github.com/NaturalHistoryMuseum/ckanext-versioned-datastore/commit/f35a4b4a08bd7f8abfd0bb68d5bd49e76b8b9f6c
> v3.6.2.1 point release

- ckanext/versioned_datastore/lib/downloads/dwc/urls.py
Mostly for the vernacular name extension, but I added several others as well because why not.
> Add more GBIF DwC extensions

- ckanext/versioned_datastore/lib/downloads/dwc/archive.py
- ckanext/versioned_datastore/lib/downloads/dwc/urls.py
Adds:
- vernacular names
- references
- description
- distribution
- species profile
- types and specimen
- identifier
From the GBIF DwC extensions: https://rs.gbif.org/extension/gbif/1.0
> Add more DwC extensions

- ckanext/versioned_datastore/helpers.py
- ckanext/versioned_datastore/plugin.py
- ckanext/versioned_datastore/theme/assets/less/download-status.less
- ckanext/versioned_datastore/theme/templates/status/download.html
Set a max height for queries on the download status page.
> Scrolling queries

- ckanext/versioned_datastore/helpers.py
- ckanext/versioned_datastore/plugin.py
- ckanext/versioned_datastore/theme/assets/less/download-status.less
- ckanext/versioned_datastore/theme/templates/status/download.html
> Weekly release 2023-02-06

- .pre-commit-config.yaml
- ckanext/versioned_datastore/theme/assets/less/search.less
- ckanext/versioned_datastore/theme/assets/less/slugerator.less
- ckanext/versioned_datastore/theme/assets/scripts/modules/search.js
- docs/_scripts/gen_api_pages.py
Notable: adds prettier and reformats js/less/vue, exclude migration scripts in API doc generation.
> Fixes for commit hooks, docs scripts, etc

- .pre-commit-config.yaml
- ckanext/versioned_datastore/theme/assets/less/search.less
- ckanext/versioned_datastore/theme/assets/less/slugerator.less
- ckanext/versioned_datastore/theme/assets/scripts/modules/search.js
- docs/_scripts/gen_api_pages.py
> Weekly release 2023-02-20

- ckanext/versioned_datastore/helpers.py
- ckanext/versioned_datastore/plugin.py
> Weekly release 2023-03-06

- ckanext/versioned_datastore/cli.py
> Patch release 2023-07-18

- ckanext/versioned_datastore/lib/downloads/download.py
- ckanext/versioned_datastore/lib/downloads/notifiers/__init__.py
- ckanext/versioned_datastore/lib/downloads/notifiers/base.py
- ckanext/versioned_datastore/lib/downloads/notifiers/email.py
- ckanext/versioned_datastore/lib/downloads/notifiers/webhook.py
- ckanext/versioned_datastore/logic/actions/downloads.py
- ckanext/versioned_datastore/theme/assets/scripts/modules/download-button.js
- ckanext/versioned_datastore/theme/templates/ajax_snippets/download_popup.html
> Patch release 2023-07-20

- .github/SUPPORT.md
- CITATION.cff
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- ckanext/versioned_datastore/lib/downloads/derivatives/dwc/generator.py
- ckanext/versioned_datastore/routes/__init__.py
- pyproject.toml
> Weekly release 2023-10-02

- ckanext/versioned_datastore/lib/downloads/derivatives/dwc/generator.py
> Patch release 2023-10-05

- ckanext/versioned_datastore/interfaces.py
- ckanext/versioned_datastore/lib/downloads/derivatives/dwc/generator.py
- ckanext/versioned_datastore/lib/downloads/download.py
- tests/integration/downloads/test_downloads.py
- tests/unit/lib/downloads/test_downloads_runmanager.py
> Patch release 2023-10-05 (part 2)

- ckanext/versioned_datastore/logic/actions/extras.py
> Weekly release 2023-10-16

- ckanext/versioned_datastore/lib/downloads/download.py
> Filter out Nones from sum resource count calculation

- ckanext/versioned_datastore/lib/downloads/download.py
- ckanext/versioned_datastore/logic/actions/multisearch.py
> Weekly release 2023-11-20

- ckanext/versioned_datastore/lib/downloads/download.py
> Hotfix: set default resource totals to 0

- ckanext/versioned_datastore/lib/downloads/download.py
- ckanext/versioned_datastore/lib/downloads/utils.py
- tests/unit/lib/downloads/test_downloads_utils.py
> fix: request index mappings in batches to avoid elasticsearch URL length error

- ckanext/versioned_datastore/lib/downloads/derivatives/xlsx.py
- ckanext/versioned_datastore/lib/downloads/download.py
- ckanext/versioned_datastore/lib/downloads/utils.py
- tests/unit/lib/downloads/test_downloads_utils.py
> Weekly release 2023-11-27

- ckanext/versioned_datastore/logic/actions/meta/help.py
- ckanext/versioned_datastore/logic/actions/meta/schema.py
- ckanext/versioned_datastore/logic/actions/multisearch.py
- ckanext/versioned_datastore/logic/auth.py
> Weekly release 2023-12-04

- .readthedocs.yaml
- ckanext/versioned_datastore/routes/datastore.py
> Weekly release 2023-12-11

- ckanext/versioned_datastore/lib/downloads/derivatives/dwc/generator.py
> Weekly release 2024-01-15

- ckanext/versioned_datastore/lib/query/schema.py
- ckanext/versioned_datastore/lib/query/utils.py
- ckanext/versioned_datastore/lib/query/v1_0_0.py
- ckanext/versioned_datastore/logic/actions/multisearch.py
- tests/unit/lib/query/test_query_utils.py
> Weekly release 2024-03-11

- ckanext/versioned_datastore/lib/datastore_utils.py
- ckanext/versioned_datastore/plugin.py
> Weekly release 2024-07-08

- ckanext/versioned_datastore/lib/datastore_utils.py
- ckanext/versioned_datastore/plugin.py
> Patch release 2024-07-08

- ckanext/versioned_datastore/logic/download/action.py
- ckanext/versioned_datastore/logic/download/auth.py
> Rename and redefine custom filename auth function

- ckanext/versioned_datastore/logic/validators.py
- tests/unit/logic/test_validators.py
> Deduplicate resource IDs during validation

- ckanext/versioned_datastore/logic/multi/action.py
Temporary fix. At some point this should be fixed by passing the "ignore_unavailable" param into the splitgill search (NaturalHistoryMuseum/splitgill#38), but for now we can at least catch the errors and return some resuts for the resources that do exist.
It really shouldn't get to this point anyway, so this is a last resort for resources that for whatever reason have made it through the previous validation steps.
Closes: #193
> Catch index NotFoundError

- ckanext/versioned_datastore/logic/validators.py
> Patch release 2025-06-17

- ckanext/versioned_datastore/logic/validators.py
Fixes the previous patch (#201), which turned out to be very slow on production.
This imports directly from `ckan.model`, which isn't ideal, but should be significantly faster.
> Improve performance of check_resource_id

- ckanext/versioned_datastore/logic/validators.py
> Patch release 2025-06-17 part 2

- ckanext/versioned_datastore/routes/search.py
> Fix slugerator

- ckanext/versioned_datastore/routes/search.py
> Weekly release 2025-07-08

- README.md
- ckanext/versioned_datastore/logic/multi/action.py
- ckanext/versioned_datastore/logic/slug/action.py
- ckanext/versioned_datastore/theme/public/querySchemas/v1.0.0/v1.0.0.yml
- docs/usage/actions.md
- docs/usage/downloads/index.md
- tests/unit/logic/actions/test_actions_slug.py
> Weekly release 2025-08-11
