NaturalHistoryMuseum/ckanext-versioned-datastore

- ckanext/versioned_datastore/lib/ingestion/feeders.py
The id must be stored in mongo as an integer, so here we force it. This came up because I created a resource from a csv without an _id field and then updated it with a new version where the _id was set. Under these
circumstances the _id is read as a string and therefore needs to be converted to an int before storage, otherwise you end up with some records where the id in mongo is an int and some where it's a string, blargh! Currently this is not a problem in the live mongo database so we can safely make this change without breaking anything, so that's lucky.
In the future, it'd be far better to validate the source before ingestion, or have a way of rolling back, however with the current version of ckan the first part of this would be a nightmare and as for the second part, that needs to …
> The id must be an int!

- ckanext/versioned_datastore/helpers.py
- ckanext/versioned_datastore/lib/ingestion/exceptions.py
- ckanext/versioned_datastore/lib/ingestion/ingesting.py
- ckanext/versioned_datastore/lib/ingestion/readers.py
- ckanext/versioned_datastore/lib/ingestion/utils.py
- ckanext/versioned_datastore/lib/stats.py
- ckanext/versioned_datastore/plugin.py
- ckanext/versioned_datastore/theme/fanstatic/css/datastore-activities.css
- ckanext/versioned_datastore/theme/templates/package/resource_data.html
- ckanext/versioned_datastore/theme/templates/package/snippets/index_message.html
- ckanext/versioned_datastore/theme/templates/package/snippets/ingest_message.html
- ckanext/versioned_datastore/theme/templates/package/snippets/prep_message.html
The table was horrible.
Now instead of something like this:
You get something like this:
There are a couple of other minor tweaks in this PR:
- fix TSV detection (https://github.com/NaturalHistoryMuseum/ckanext-versioned-datastore/commit/6673f7468f0a65ff7042b481b16ebdd78d0bb412)
- fix universal lines issue (https://github.com/NaturalHistoryMuseum/ckanext-versioned-datastore/commit/36d077ac8ee630e44abd51bdc4818e7572586d85)
- provide row count progress on prep operations (https://github.com/NaturalHistoryMuseum/ckanext-versioned-datastore/commit/e2e84e1e815adde8c5e080c2a81d592c46f70927)
- try to catch rubbish unicode uploads (https://github.com/NaturalHistoryMuseum/ckanext-versioned-datastore/commit/6f0ac4beb993b0806e56569ba542e8464889e665)
> Improve the datastore page's styling

- ckanext/versioned_datastore/logic/action.py
- ckanext/versioned_datastore/logic/auth.py
- ckanext/versioned_datastore/logic/schema.py
- ckanext/versioned_datastore/plugin.py
This action allows counting the number of records, at a given version, in either all or a specific set of public resources.
Prompted by https://github.com/NaturalHistoryMuseum/data-portal/issues/360 but useful anyway.
> Add a dedicated cross-resource counting action

- ckanext/versioned_datastore/logic/actions/multisearch.py
This adds the modified field to the sort order of `datastore_multisearch` responses. There are two reasons to add this:
1. It provides a workaround for the problems we are currently having with the gallery and thumbnails from MAM - though not directly. Sorting by `modified`, `_id` and then `index` produces a couple of pages worth of results before the dreaded "Image not Found" error image comes up, whereas without the `modified` field in the sort the first page is full of "Image not Found" error images.
2. It mirrors the old view functionality.
> Add modified field to default sort

- ckanext/versioned_datastore/lib/downloads/jsonl.py
- ckanext/versioned_datastore/lib/downloads/sv.py
- ckanext/versioned_datastore/lib/downloads/utils.py
This may seem like a pointless exercise as surely if the field count is 0 for a field then it won't appear in any of the data dicts - however, because the data returned from elasticsearch is the source dict that was uploaded to it, it could contain nulls and empty string values. The calculate_field_counts function that generates the field counts does it by using exist queries and because these count indexed values it skips
nulls and empty strings which are ignored during indexing.
Fixes https://github.com/NaturalHistoryMuseum/ckanext-versioned-datastore/issues/32
> Only write fields that exist

- ckanext/versioned_datastore/interfaces.py
- ckanext/versioned_datastore/lib/downloads/download.py
- tests/test_download.py
On the NHM's Office365 email client we have some URL safety checking service that alters the URLs in emails to put them through a safety filter. This mangles the emails something chronic and they end up looking something like this:
This PR fixes that by sending HTML emails for downloads from the versioned datastore plugin. This results in emails that look like this instead:
Much nicer!
This change has a breaking interface change in it and therefore will require a new major version when tagged for release.
> Send HTML download emails

- README.md
- ckanext/versioned_datastore/lib/downloads/download.py
- ckanext/versioned_datastore/lib/downloads/dwc/__init__.py
- ckanext/versioned_datastore/lib/downloads/dwc/archive.py
- ckanext/versioned_datastore/lib/downloads/dwc/schema.py
- ckanext/versioned_datastore/lib/downloads/dwc/schema_parts.py
- ckanext/versioned_datastore/lib/downloads/dwc/urls.py
- ckanext/versioned_datastore/lib/downloads/dwc/utils.py
- ckanext/versioned_datastore/lib/downloads/dwc/writer.py
- ckanext/versioned_datastore/logic/actions/downloads.py
- ckanext/versioned_datastore/logic/schema.py
- setup.py
Adds a new download format - [DarwinCore Archives](https://dwc.tdwg.org/text). Closes #22.
- supports core extensions and non-core extensions (currently only configured to use GBIF extensions)
- extensions can be set in configs and overridden in request args
- optionally integrates with [ckanext-attribution](https://github.com/NaturalHistoryMuseum/ckanext-attribution) and [ckanext-query-dois](https://github.com/NaturalHistoryMuseum/ckanext-query-dois) to generate metadata (uses defaults if not available)
- also adds `format_args` request arg for all download types, for passing in extra options specific to the format
> DwC-A downloader

- ckanext/versioned_datastore/lib/downloads/download.py
- ckanext/versioned_datastore/lib/importing/queuing.py
Add timeouts of 600 seconds to download and import jobs.
> Add job timeouts

- ckanext/versioned_datastore/lib/downloads/utils.py
- setup.py
Fixes bug where elasticsearch would crash while counting fields in `calculate_field_counts`.
> Use aggregations to count non-empty fields

- ckanext/versioned_datastore/lib/downloads/download.py
- setup.py
Generally this isn't a problem, but for very large queries (e.g. geo polygon type queries) timeouts can occur:
`elasticsearch.exceptions.ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='157.140.17.34', port=9200): Read timed out. (read timeout=10))`
This just extends the timeout a little.
> Extend the elasticsearch client timeout to 30s instead of 10s

- ckanext/versioned_datastore/interfaces.py
- ckanext/versioned_datastore/lib/downloads/download.py
Particularly useful for extensions like [ckanext-query-dois](https://github.com/NaturalHistoryMuseum/ckanext-query-dois), so any download/search metadata (e.g. a DOI) can be created _before_ the download file is created and can then be included in the file.
> Add an interface hook to modify request before writing download file

- dev_requirements.txt
- docker-compose.yml
- docker/Dockerfile
- pyproject.toml
- requirements.txt
- setup.cfg
- setup.py
More modern! Bit better! Also, fixes the problem where when ckanext-nhm installs this repo as a dependency but doesn't install all the dependencies correctly (specifically, nhm -> this repo -> pandas but then fails to install numpy).
> Switch to setup.cfg

- ckanext/versioned_datastore/logic/actions/downloads.py
- ckanext/versioned_datastore/logic/actions/multisearch.py
- ckanext/versioned_datastore/logic/schema.py
- ckanext/versioned_datastore/routes/search.py
- `datastore_resolve_slug` now resolves DOIs as well as slugs (slugs have priority)
- added `slug_or_doi` param to `datastore_queue_download` so a saved query can be used instead of having to provide the whole query every time
closes #57
> Download with slug or DOI

- ckanext/versioned_datastore/lib/downloads/download.py
- ckanext/versioned_datastore/lib/downloads/xlsx.py
- docker-compose.yml
- tests/test_xlsx_downloader.py
Fixes https://github.com/NaturalHistoryMuseum/data-portal/issues/437 by allowing users to download the data in XLSX format and use it straight up instead of in CSV and importing it.
> Add an XLSX file download option

- ckanext/versioned_datastore/logic/actions/help.py
- ckanext/versioned_datastore/logic/actions/multisearch.py
- ckanext/versioned_datastore/logic/auth.py
- ckanext/versioned_datastore/logic/schema.py
- ckanext/versioned_datastore/plugin.py
Allows users to edit or add reserved slugs for queries. Any logged-in user can add a reserved slug where one does not already exist, but only sysadmins can edit or replace existing ones.
> Add datastore_edit_slug action

- ckanext/versioned_datastore/lib/importing/ingestion/readers.py
We check for empty cells but we can also check if the cell value is None too so we might as well.
> fix: catch null values in xlsx files better

- ckanext/versioned_datastore/lib/downloads/download.py
- ckanext/versioned_datastore/lib/downloads/notifiers/__init__.py
- ckanext/versioned_datastore/lib/downloads/notifiers/base.py
- ckanext/versioned_datastore/lib/downloads/notifiers/email.py
- ckanext/versioned_datastore/lib/downloads/notifiers/webhook.py
- ckanext/versioned_datastore/logic/actions/downloads.py
- ckanext/versioned_datastore/theme/assets/scripts/modules/download-button.js
- ckanext/versioned_datastore/theme/templates/ajax_snippets/download_popup.html
Users were able to (and were doing so repeatedly) submit the popup form with incorrect or blank email addresses. The download failed immediately because it wasn't able to send the "starting" notification, but the status in the database didn't change from "initiated".
Three things done in this PR:
- stop users being able to submit the popup form with bad or blank emails
- add email and webhook validation so if they do still manage to submit a request, it doesn't make it to the download queue and they get a sensible error message
- added the notifier call to the try-except section so if it fails, we know about it
> Fix notifier bugs, add email validation

- ckanext/versioned_datastore/theme/templates/ajax_snippets/download_popup.html
Multiple emails are allowed by the API, but I never implemented a way of getting them into a list from the textbox.
> Remove the text saying multiple emails are allowed

- ckanext/versioned_datastore/lib/downloads/derivatives/dwc/generator.py
- ckanext/versioned_datastore/routes/__init__.py
Adding `eml_title` as a `format_arg` replaces the "Query on [site title]".
This PR also includes a bonus fix for the debug direct download route, which wasn't being loaded because there are multiple `debug` variables.
> Allow users to specify a custom title for DwC downloads

- ckanext/versioned_datastore/interfaces.py
- ckanext/versioned_datastore/lib/downloads/derivatives/dwc/generator.py
- ckanext/versioned_datastore/lib/downloads/download.py
- tests/integration/downloads/test_downloads.py
- tests/unit/lib/downloads/test_downloads_runmanager.py
- minor EML bugfix: fixes the very silly bug where I used 0 instead of 1 when checking the length of the resource/package lists
- adds a `download_after_init` hook that runs at the end of the `DownloadRunManager` setup; intended to be used to generate the query DOI (via ckanext-query-dois) earlier in the process, rather than at the end when the manifest is being written.
> Add another download hook, EML bugfix

- ckanext/versioned_datastore/logic/actions/extras.py
`datastore_get_resource_versions` is slow and it's taking longer than NGINX is willing to wait so we're getting timeouts. Increasing the NGINX proxy timeout is possible but it's not the best solution, making the action faster is better 🙂 
To get it to go faster, the action has been switched from using individual count requests to the elasticsearch cluster to `msearch` batches. Tested on staging and seems to be a big improvement.
Fixes https://github.com/NaturalHistoryMuseum/ckanext-versioned-datastore/issues/130
> Increase performance in datastore_get_resource_versions action

- ckanext/versioned_datastore/logic/actions/multisearch.py
Sets the limit to 500. The default is still 20.
> Increase datastore_value_autocomplete results limit

- ckanext/versioned_datastore/lib/downloads/derivatives/dwc/generator.py
- the core file and any extensions need a common field/identifier to join on
- we use `_id` because every record has an `_id` field
- the multimedia extension pulls its data from `associatedMedia`, which _also_ has its own separate `_id` (the IRN of the image)
- this was overwriting the record `_id`, so the identifiers did not match up
- the media `_id` is fairly useless for external viewers, so ignoring it when processing records for DwC export is the quickest and easiest way to fix this issue
> Hotfix: ignore `_id` field in extension rows

- ckanext/versioned_datastore/lib/downloads/download.py
Causes issues with stats (and also just doesn't make much sense) if some counts are integers and others are nulls.
> Set default resource totals to 0

- ckanext/versioned_datastore/lib/downloads/derivatives/xlsx.py
I'm not 100% sure this catches the problem as I couldn't recreate it locally (it must be an error at a very specific point or something?) but this has a decent chance of fixing the problem of a temporary workbook being left around in /tmp after we've finished/errored the download.
Closes: #118
> fix: ensure the workbook is closed if something goes wrong during the write call

- ckanext/versioned_datastore/logic/actions/multisearch.py
date modified was causing issues with some datasets; es would generate a huge integer instead of the actual modified date, then wouldn't be able to handle that huge integer. using version achieves basically the same thing, though is slightly less precise.
> fix: sort on version rather than date modified

- ckanext/versioned_datastore/lib/query/schema.py
- ckanext/versioned_datastore/lib/query/utils.py
- ckanext/versioned_datastore/lib/query/v1_0_0.py
- ckanext/versioned_datastore/logic/actions/multisearch.py
- tests/unit/lib/query/test_query_utils.py
Convert OR groups with one item to AND, and remove empty groups. These changes don't alter the meaning of the query, but they will prevent some common errors.
Also includes \~unit tests\~ (ooooh).
Closes #157
> Fix some query errors before running

- ckanext/versioned_datastore/lib/datastore_utils.py
- ckanext/versioned_datastore/plugin.py
- removes the hacky method that adds temporary jobs to queues in order to get an accurate queue length; it now isn't as accurate but it doesn't break everything, so that's probably better
- increases the tolerance for queue lengths; i.e. it will only reach "amber" alert when there are 2 queued items (not including currently processing) and "bad" when there are 4
> Status patches

- ckanext/versioned_datastore/routes/status.py
Errors can be raised, for example, when a resource is a non-datastore resource.
Fixes #175
> Eat exceptions when attempting to resolve a query doi

- pyproject.toml
Update vds to new version of Splitgill which fixes the [index op generation bug](https://github.com/NaturalHistoryMuseum/splitgill/issues/34).
> Update splitgill to v3.1.0

- ckanext/versioned_datastore/logic/basic/action.py
- ckanext/versioned_datastore/logic/basic/utils.py
- ckanext/versioned_datastore/logic/multi/action.py
- ckanext/versioned_datastore/logic/multi/auth.py
- ckanext/versioned_datastore/logic/multi/helptext.py
- ckanext/versioned_datastore/logic/multi/schema.py
- tests/unit/logic/basic/test_utils.py
We used to have `datastore_search_raw` which allowed users to query elasticsearch directly using normal elasticsearch queries. This is not great so it was removed in v6, but it does have a use, so it's been readded with the restriction that it's only available to admin users. This means if you want to use it via the API you need to provide the appropriate authentication, but it does still allow other extensions to use it by passing ignore_auth in their context dict.
The readded action is called `vds_multi_direct`.
> Recreate a raw elasticsearch search action

- ckanext/versioned_datastore/logic/slug/action.py
This sets the resource version for the query to the newest (maximum) version of all the resources in the `resources_and_versions` dict when the `requested_version` is not set.
This is a fix for #187 that has a major caveat: the newest version in the list may not resolve to the originally intended version for all resources in the list.
This was tested on the NHM's dataset and only found to be a problem for a small number of potentially affected DOIs, and all of the affected resources were "special" resources that were loaded and versioned in a non-standard way. Obviously we are unable to test it on anyone else's implementation (if there _are_ any other usages of this extension) but from this we're relatively confident that it shouldn't be a problem for standard datasets and resources.
> Query DOI versions

- ckanext/versioned_datastore/lib/query/search/request.py
- tests/unit/lib/query/test_request.py
Sometimes it's helpful to be able to pass parameters to ES to control the search, this feature supports doing that using the new `add_param` method on `SearchRequest`.
> Allow ES parameters to be passed with search requests

- ckanext/versioned_datastore/logic/multi/utils.py
- ckanext/versioned_datastore/theme/assets/webassets.yml
- ckanext/versioned_datastore/theme/templates/search/search.html
Adds `ignore_unavailable` parameter to multisearch requests as a quick fix for "search everything" not working.
Also fixes the search asset reference.
> Ignore unavailable resources

- ckanext/versioned_datastore/logic/slug/action.py
- tests/unit/logic/actions/test_actions_slug.py
Filters missing or inaccessible resources from the list of `resource_ids` in a resolved slug or DOI and either:
- provide a warning if there are other resources still available
- return an error if all resources are now invalid
Closes: #192
> Filter invalid resources + warn

- ckanext/versioned_datastore/logic/slug/action.py
- tests/unit/logic/actions/test_actions_slug.py
Resolving slugs/DOIs with a lot of resources is very slow because we need to make sure that they're all available in the datastore. Previously we were iterating over them and checking each one individually to make sure it exists, is accessible by the current user, and is in the datastore.
This loads a set of resource IDs from the database that are marked as `datastore_active` and checks the slug/DOI's resources against that. This means we're no longer checking against the datastore directly and therefore are relying on the database to be accurate. Not ideal, but iterating and checking directly was just way too slow.
Closes: #210
> Improve performance of slug resolution action
